[build]
  command = "npm run build"
  publish = "client/build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/graphql"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200